### ISSUE TITLE
API action. Create folder

### ISSUE THREAD

**Issue by n0str** [codex-team/codex.notes#51]
**Fields**

[+user ID]

1. Folder ID
2. Folder Name
3. Create Timestamp

**Comment by gohabereg** [comment]
DB Schema
![image](https://user-images.githubusercontent.com/23050529/32236003-0a0e6964-be72-11e7-8b63-1cdda83b6249.png)

**Comment by demyashev** [comment]
`$ curl -X POST --data 'user=xhr3y0tm&name=testname' http://codex.notes.server/v1/folder/create`

**Comment by demyashev** [comment]
{'did': 'd123', 'shared': [{'user_id': 'u123'},...], title: "this is the title", 'timestamp': 52176312}
