### ISSUE TITLE
[design] Login dialog with two buttons:

### ISSUE THREAD

**Issue by n0str** [codex-team/codex.notes#61]
- offline
- Google sign in

**Comment by neSpecc** [comment]
1. Offline 

![image](https://user-images.githubusercontent.com/3684889/32690536-4ea944aa-c709-11e7-963d-0e6fdfc7b6b3.png)

2. Offline - avatar hovered

![image](https://user-images.githubusercontent.com/3684889/32690539-5c5f9ad6-c709-11e7-9671-838daa2177e8.png)

3. Online 

![image](https://user-images.githubusercontent.com/3684889/32690542-68172b46-c709-11e7-8b8e-1ad08ec5134a.png)

Label `Offline` my accepts several statuses:
- Offline
- Reconnection...
- Syncing... (on saving)
- All synced (online, all saved)

When online user clicks on the `Set picture` icon, we save selected image as his avatar.

![image](https://user-images.githubusercontent.com/3684889/32690565-d756834e-c709-11e7-8b7d-1ec08f806e73.png)
