### ISSUE TITLE
Aside panel with avatar and popup

### ISSUE THREAD

**Issue by n0str** [codex-team/codex.notes#64]
Create aside panel according to the design from https://github.com/codex-team/codex.notes/issues/61

￼
![32690536-4ea944aa-c709-11e7-963d-0e6fdfc7b6b3](https://user-images.githubusercontent.com/988885/33331603-189df578-d473-11e7-912d-7e9f71397cd5.png)

![32690539-5c5f9ad6-c709-11e7-9671-838daa2177e8](https://user-images.githubusercontent.com/988885/33331610-1be408ee-d473-11e7-9c0f-29ecd7654bce.png)

**Comment by neSpecc** [comment]
Done with #82
